@baseUrl =  http://localhost:3000/api/bill-details

# User API

# @name Getall
GET {{baseUrl}} 

###

# @name GetbyId
GET {{baseUrl}}/6455ceffc8d917d3615a497b

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
   "name":"demo 1",
   "urlImg": "demo 1",
   "price": 1234,
   "quantity": 1234,
   "total": 1234,
   "billId": "6485d9ee64438f7d6f4ee144",
   "productId": "6455d0c5c8d917d3615a4995"
}

###

# @name Update
PUT {{baseUrl}}/update/6485d7665bdaad0ae2be68c3
Content-Type: application/json

{
   "paymentMethod":"Demo 1",
   "shippingMethod":"Dmeo 1",
   "shippingFee":1234,
   "total":234,
   "customerId":"648567df63cc33b32a1d7933",
   "userId":"648567df63cc33b32a1d7933"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/6485d7665bdaad0ae2be68c3

###