@baseUrl =  http://localhost:3000/api/bills

# User API

# @name Getall
GET {{baseUrl}} 

###

# @name GetbyId
GET {{baseUrl}}/6455ceffc8d917d3615a497b

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
"paymentMethod":"Demo",
"shippingMethod":"Dmeo",
"shippingFee":1234,
"total":234,
"customerId":,
"userId":,
}

###

# @name Update
PUT {{baseUrl}}/update/6455ceffc8d917d3615a497a
Content-Type: application/json

{
   "name": "Đèn"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/6455ceffc8d917d3615a497b

###